spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/wangzhe
    username: root
    password: 123456
mybatis:
  mapper-locations: com/atu/mapper/*.xml
